project:
  type: website

website:
  title: "#AASC2026"
  page-footer: |
    Sponsored by [VSNi](https://vsni.co.uk/)  
    ![](/images/sponsors/VSNi_logo.png){fig-alt="VSNi" height="4em"}  
    <br><br>
    Australasian Applied Statistics Conference, Sunshine Coast, Australia
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: Program
        menu: 
          -  href: keynote.qmd
          -  href: workshop.qmd
          - href: social.qmd
      - abstracts.qmd 
      - registration.qmd
      - text: About 
        menu: 
          - location.qmd
          - accomodation.qmd
          - organisers.qmd
format:
  html:
    code-fold: true
    collapsible: true
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
editor: visual

