---
title: Registration
---

# Conference registration is now open

Please select the following link to [**register for the AASC2026 conference.**](https://www.eventbrite.com.au/e/australasian-applied-statistics-conference-2026-tickets-1990841421283?aff=oddtdtcreator)

## Conference registration prices:

The following table outlines the conference registration prices in \$AUD:

<div class="table-responsive">
<table class="table table-striped table-hover">
  <thead class="table-light">
    <tr>
      <th>Item</th>
      <th class="text-end">Early-bird rate (AUD)</th>
      <th class="text-end">Standard rate (AUD)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Full conference registration<sup>1</sup></td>
      <td class="text-end">996</td>
      <td class="text-end">1165</td>
    </tr>
    <tr>
      <td>Full conference registration<sup>1,3</sup> (student)</td>
      <td class="text-end">699</td>
      <td class="text-end">848</td>
    </tr>
    <tr>
      <td>Full-day workshop<sup>2</sup></td>
      <td class="text-end"></td>
      <td class="text-end">319</td>
    </tr>
    <tr>
      <td>Half-day workshop<sup>2</sup></td>
      <td class="text-end"></td>
      <td class="text-end">234</td>
    </tr>
    <tr>
      <td>Full-day registration only<sup>2</sup> (Tuesday or Thursday)</td>
      <td class="text-end"></td>
      <td class="text-end">372</td>
    </tr>
    <tr>
      <td>Half-day registration only<sup>2</sup> (Wednesday or Friday)</td>
      <td class="text-end"></td>
      <td class="text-end">319</td>
    </tr>
    <tr>
      <td>Welcome reception extra guest</td>
      <td class="text-end"></td>
      <td class="text-end">129</td>
    </tr>
    <tr>
      <td>Conference dinner (Thursday evening) extra guest</td>
      <td class="text-end"></td>
      <td class="text-end">182</td>
    </tr>
  </tbody>
</table>
</div>
------------------------------------------------------------------------

### Notes:

1.  Full conference registration includes attendance of all conference days, at the welcome reception, poster session, and the conference dinner. Pre-conference workshop registration is separate.
2.  Day registrations include morning tea, lunch, and continuous tea/coffee.
3.  To access the student discount, you must be a student currently completing postgraduate (masters or PhD) research at a recognised university. To apply for the student discount, please email [the secretary](mailto:michael.mumford@dpi.qld.gov.au) declaring that you are a student at the corresponding research institution. A letterhead written by the student's primary supervisor must be included in the email.

## Conference dinner

The conference dinner will be held at [Marina Mooloolaba](https://marinamooloolaba.au/) on Thursday evening the 3rd December from 5pm-10pm.

The dress code for the conference dinner is **smart casual**. The conference dinner venue is a premium waterfront dining and events destination. If in doubt, dress up!

Further details on the conference dinner will be provided soon!

## Conference workshops

[Click here](https://aasc2026.netlify.app/workshop) for more information about the pre-conference workshops

## Social activities

+-------+----------------------------------+----------------------------------------------------------------------------------------+---------------------------+------------------+-------+
| \#    | Name                             | Description                                                                            | Time and Duration         | Location         | Price |
+=======+==================================+========================================================================================+===========================+==================+=======+
| 1     | **Walking along the oceanfront** | Enjoy a guided group walk along Mooloolaba and Maroochydore oceanfront.\               | 1:30pm–3:30pm             | Mooloolaba Beach | \$0   |
|       |                                  | \                                                                                      |                           |                  |       |
|       |                                  |                                                                                        |                           |                  |       |
|       |                                  | - **1:30pm – 2:00pm:** Explore the rocky beachfront across from the Mantra Mooloolaba. |                           |                  |       |
|       |                                  |                                                                                        |                           |                  |       |
|       |                                  | - **2:00pm – 3:30pm:** Walk north along the oceanfront to Maroochydore Beach and back. |                           |                  |       |
|       |                                  |                                                                                        |                           |                  |       |
|       |                                  | - **3:30pm onwards:** Optional refreshments or additional walking.                     |                           |                  |       |
+-------+----------------------------------+----------------------------------------------------------------------------------------+---------------------------+------------------+-------+
| 2     | **Aquaduck**                     | Explore Mooloolaba by land and sea on the Aquaduck Sunshine Coast.\                    | 2:00pm (1 hour)           | Near SEA LIFE    | \$60  |
|       |                                  | \                                                                                      |                           |                  |       |
|       |                                  |                                                                                        |                           |                  |       |
|       |                                  | - Departs directly in front of SEA LIFE Sunshine Coast.                                |                           |                  |       |
|       |                                  |                                                                                        |                           |                  |       |
|       |                                  | - Combines the best sights of Mooloolaba into one fun and exciting tour.               |                           |                  |       |
+-------+----------------------------------+----------------------------------------------------------------------------------------+---------------------------+------------------+-------+
| 3     | **Mooloolaba Canal Cruise**      | Relaxing sunset cruise through the calm waters of the Mooloolah River.\                | 5:00pm (arrive by 4:45pm) | Mooloolaba Wharf | \$38  |
|       |                                  | \                                                                                      |                           |                  |       |
|       |                                  |                                                                                        |                           |                  |       |
|       |                                  | - Departs from Mooloolaba Wharf.                                                       |                           |                  |       |
|       |                                  |                                                                                        |                           |                  |       |
|       |                                  | - Enjoy live commentary about the region’s history and significance.                   |                           |                  |       |
+-------+----------------------------------+----------------------------------------------------------------------------------------+---------------------------+------------------+-------+
| 4     | **Ginger Factory**               | Tour the world’s largest operating ginger factory and enjoy its attractions.\          | 1:45pm–5:40pm             | Yandina          | \$86  |
|       |                                  | \                                                                                      |                           |                  |       |
|       |                                  |                                                                                        |                           |                  |       |
|       |                                  | - Tastes of Ginger tour.                                                               |                           |                  |       |
|       |                                  |                                                                                        |                           |                  |       |
|       |                                  | - Live Bee Show.                                                                       |                           |                  |       |
|       |                                  |                                                                                        |                           |                  |       |
|       |                                  | - Ginger Train Ride.                                                                   |                           |                  |       |
+-------+----------------------------------+----------------------------------------------------------------------------------------+---------------------------+------------------+-------+
| 5     | **Montville**                    | Explore shops, galleries, and cafés in Montville.\                                     | 1:00pm–5:10pm             | Montville        | \$44  |
|       |                                  | \                                                                                      |                           |                  |       |
|       |                                  |                                                                                        |                           |                  |       |
|       |                                  | - Free time to explore the main strip.                                                 |                           |                  |       |
|       |                                  |                                                                                        |                           |                  |       |
|       |                                  | - Optional group afternoon tea at Poets Café at 3pm.                                   |                           |                  |       |
+-------+----------------------------------+----------------------------------------------------------------------------------------+---------------------------+------------------+-------+

[Click here](https://aasc2026.netlify.app/social) for more information about the conference social activities

## Travel insurance

We recommend you to get travel insurance.

## Cancellation policy

Cancellations must be notified in writing to [the conference organisers](mailto:michael.mumford@dpi.qld.gov.au)

Cancellations notified before 1st October 2026 will be given an 80% refund. After this date, but prior to 14th November the refund will be 50%. After 14th November 2026, there will be no refund. This policy applies to conference registrations and to the social program.

## While registering, accept AGUAi membership

Despite its name, the Australasian Genstat Users Association Inc (AGUAi) exists specifically to organise this biennial conference. As you register for the conference, please accept free membership. You will then be placed on the conference email list to stay informed about future AASC conferences and be eligible to vote on who gets to organise the next AASC. For historical reasons, the formal objectives of the association are:

- To foster association between persons involved or interested in the application of statistical methods

- To foster association between persons involved or interested in using Genstat

- To organise meetings and events focused on statistical and statistical computing issues.

The Rules of Association are available <a href="files/AGUAi_rules_of_Association.pdf" download>here</a>.
